In [2]:
import pandas as pd

In [4]:
pd.read_parquet("predata/datafiles_2025-10-28.parquet")

,6,2,1,3,5
0,s390148813.java,s821263993.java,s986612929.java,s330489063.java,s346313177.java
1,s535206386.java,s957112767.java,s624144969.java,s056104035.java,s509409020.java
2,s516143404.java,s629227777.java,s227971449.java,s279911710.java,s687301013.java
3,s946785630.java,s194569674.java,s566715655.java,s865455681.java,s919393581.java
4,s797152006.java,s136711388.java,s994202269.java,s798928543.java,s483515897.java
...,...,...,...,...,...
295,s025031481.java,s184968744.java,s830635380.java,s381665110.java,s185963250.java
296,s976124072.java,s021798406.java,s907936630.java,s645975376.java,s981593319.java
297,s388372913.java,s173879393.java,s507035370.java,s539920102.java,s050673760.java
298,s450805923.java,s600512752.java,s226739958.java,s918835910.java,s149065934.java
299,s578800226.java,s662339778.java,s211966081.java,s970170099.java,s581579443.java

In [2]:
import pandas as pd
from pathlib import Path
import pandas as pd
import os

pd.read_parquet("predata/similarities_2025-10-29_11:09.parquet")

,g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00006_f:s390148813.java,g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00002_f:s821263993.java,g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00001_f:s986612929.java,g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00003_f:s330489063.java,g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00005_f:s346313177.java,g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00006_f:s535206386.java,g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00002_f:s957112767.java,g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00001_f:s624144969.java,g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00003_f:s056104035.java,g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00005_f:s509409020.java,...,g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00006_f:s450805923.java,g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00002_f:s600512752.java,g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00001_f:s226739958.java,g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00003_f:s918835910.java,g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00005_f:s149065934.java,g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00006_f:s578800226.java,g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00002_f:s662339778.java,g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00001_f:s211966081.java,g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00003_f:s970170099.java,g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00005_f:s581579443.java
g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00006_f:s390148813.java,0.977492,0.311897,0.344411,0.274232,0.278557,0.302251,0.337621,0.305466,0.288344,0.243736,...,0.331190,0.321543,0.363344,0.302251,0.393846,0.305466,0.269231,0.310345,0.191413,0.346154
g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00002_f:s821263993.java,0.311897,0.972727,0.353474,0.245863,0.192385,0.450450,0.504545,0.445415,0.230061,0.218679,...,0.432314,0.500000,0.303922,0.362140,0.332308,0.330435,0.258974,0.301724,0.152057,0.339744
g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00001_f:s986612929.java,0.344411,0.353474,0.996979,0.288416,0.210421,0.374622,0.368580,0.441088,0.293051,0.232346,...,0.365559,0.365559,0.311178,0.335347,0.320242,0.229607,0.269231,0.445402,0.200358,0.308157
g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00003_f:s330489063.java,0.274232,0.245863,0.288416,0.952719,0.234469,0.252955,0.245863,0.241135,0.281324,0.248292,...,0.248227,0.241135,0.288416,0.278960,0.283688,0.217494,0.217494,0.278960,0.212880,0.257683
g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00005_f:s346313177.java,0.278557,0.192385,0.210421,0.234469,0.975952,0.166333,0.190381,0.168337,0.284569,0.356713,...,0.188377,0.190381,0.280561,0.182365,0.272545,0.286573,0.296593,0.196393,0.305903,0.272545
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00006_f:s578800226.java,0.305466,0.330435,0.229607,0.217494,0.286573,0.317391,0.330435,0.308696,0.389571,0.287016,...,0.373913,0.288618,0.398693,0.308642,0.326154,0.965217,0.351282,0.255747,0.243292,0.269231
g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00002_f:s662339778.java,0.269231,0.258974,0.269231,0.217494,0.296593,0.246154,0.253846,0.243590,0.351282,0.348519,...,0.243590,0.282051,0.394872,0.223077,0.274359,0.351282,0.953846,0.246154,0.261181,0.210256
g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00001_f:s211966081.java,0.310345,0.301724,0.445402,0.278960,0.196393,0.293103,0.298851,0.367816,0.244253,0.223235,...,0.290230,0.301724,0.264368,0.293103,0.298851,0.255747,0.246154,0.985632,0.191413,0.298851
g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00003_f:s970170099.java,0.191413,0.152057,0.200358,0.212880,0.305903,0.168157,0.169946,0.169946,0.298748,0.280859,...,0.180680,0.175313,0.268336,0.194991,0.221825,0.243292,0.261181,0.191413,0.994633,0.194991
g:/home/ohodi/Documents/CodeSimilarity/SimilarityTool/predata/p00005_f:s581579443.java,0.346154,0.339744,0.308157,0.257683,0.272545,0.259615,0.339744,0.272436,0.266871,0.225513,...,0.288462,0.326923,0.262821,0.317308,0.347692,0.269231,0.210256,0.298851,0.194991,1.022436

In [6]:
filename = Path("predata/similarities_2025-10-29_11:09.parquet")
datafiles = Path("./predata/datafiles_2025-10-29.parquet")

similarities = load_parquet(filename)

testfile = File(os.getcwd() / Path("predata/p00005/s581579443.java"))

(train_classes, test_class) = split_classes(os.getcwd() / Path("./predata"))
training_files, test_files, _, _ = split_collected_data(datafiles, train_classes)

match = classify_best_match(similarities, training_files.flatten(), testfile)

NameError: name 'load_parquet' is not defined